/* CounselBook - library of 50 counselling activities.
 * ws = printable worksheet spec:
 *   {t:'text', v}            instruction paragraph
 *   {t:'lines', q, n}        prompt with n writing lines
 *   {t:'scale', q, min, max} 1-10 rating
 *   {t:'boxes', items, cols, h}  labelled boxes to write/draw in
 *   {t:'table', cols, rows}  table with blank rows
 *   {t:'check', q, items}    tick list
 *   {t:'draw', q, h}         large drawing space
 *   {t:'faces', q}           circle-a-face row
 * tool = id of a built-in interactive tool (see tools.js)
 */
window.ACTIVITIES = [
  // ---------------- Emotions & Feelings ----------------
  {
    id: 'a01', title: 'Feelings Thermometer', cat: 'Emotions & Feelings', grades: '3-10', mins: 15, mode: 'Worksheet',
    goal: 'Help students notice the intensity of a feeling and choose a matching coping step.',
    materials: 'Worksheet, coloured pencils',
    steps: ['Explain that feelings can be small, medium or big, like temperature.', 'Students colour the thermometer up to how strong a chosen feeling is right now.', 'For each zone (cool, warm, hot) they write one thing that helps them cool down.', 'Pair-share one cooling strategy.'],
    debrief: ['What are the early warning signs that you are moving into the "hot" zone?', 'Which cooling idea will you try this week?'],
    ws: [
      { t: 'text', v: 'Pick one feeling you had this week. Colour the thermometer to show how strong it was (1 = tiny, 10 = huge).' },
      { t: 'scale', q: 'How strong was the feeling?', min: 'Cool & calm', max: 'Boiling hot' },
      { t: 'lines', q: 'The feeling was:', n: 1 },
      { t: 'boxes', items: ['Cool zone (1-3): what I notice in my body', 'Warm zone (4-7): what I notice', 'Hot zone (8-10): what I notice'], cols: 3, h: 110 },
      { t: 'lines', q: 'Three things that cool me down:', n: 3 },
    ],
  },
  {
    id: 'a02', title: 'Emotion Charades', cat: 'Emotions & Feelings', grades: '3-8', mins: 20, mode: 'Group',
    goal: 'Build emotional vocabulary and practise reading body language.',
    materials: 'Feeling cards (or use the Question Spinner, Feelings deck)',
    steps: ['Students take turns picking a feeling card.', 'They act it out without words for 30 seconds.', 'The group guesses the feeling and names one clue (face, posture, hands).', 'Discuss a time each feeling is normal and healthy.'],
    debrief: ['Which feelings were hardest to guess? Why?', 'How can we tell what a friend feels when they do not say it?'],
    tool: 'spinner',
  },
  {
    id: 'a03', title: 'Feelings Wheel Explorer', cat: 'Emotions & Feelings', grades: '6-12', mins: 15, mode: 'Interactive',
    goal: 'Move from broad feelings (sad, angry) to precise words (lonely, frustrated).',
    materials: 'Projector or screen with the Feelings Wheel tool',
    steps: ['Open the Feelings Wheel tool on screen.', 'Ask: "Which core feeling is closest to your week?"', 'Click it to reveal more precise words; students choose the most accurate one privately.', 'Volunteers share why the precise word fits better.'],
    debrief: ['How does naming a feeling precisely help us deal with it?'],
    tool: 'feelings',
    ws: [
      { t: 'lines', q: 'My core feeling this week:', n: 1 },
      { t: 'lines', q: 'The more precise word is:', n: 1 },
      { t: 'lines', q: 'What happened that made me feel this way?', n: 3 },
      { t: 'lines', q: 'What do I need right now?', n: 2 },
    ],
  },
  {
    id: 'a04', title: 'Mood Meter Check-in', cat: 'Emotions & Feelings', grades: '3-12', mins: 10, mode: 'Interactive',
    goal: 'A quick daily check-in that maps energy and pleasantness.',
    materials: 'Mood Meter tool on screen',
    steps: ['Each student taps the quadrant that matches their mood (or points to it).', 'The tool keeps an anonymous class tally.', 'Discuss strategies to shift from red/blue zones toward green.'],
    debrief: ['What helps you move from a "red" to a "green" feeling?'],
    tool: 'moodmeter',
  },
  {
    id: 'a05', title: 'Body Map of Feelings', cat: 'Emotions & Feelings', grades: '3-9', mins: 20, mode: 'Worksheet',
    goal: 'Connect emotions with physical sensations.',
    materials: 'Worksheet, colours',
    steps: ['Students choose colours for 4 feelings (e.g. red = anger, blue = sadness).', 'They colour where on the body outline they feel each emotion.', 'Share: "When I am nervous, I feel it in my..."'],
    debrief: ['Why does noticing the body help us calm down sooner?'],
    ws: [
      { t: 'text', v: 'Choose a colour for each feeling. Colour the places on the body where you feel it.' },
      { t: 'table', cols: ['Feeling', 'My colour', 'Where I feel it'], rows: 4 },
      { t: 'draw', q: 'Draw a body outline and colour it in:', h: 300 },
    ],
  },
  {
    id: 'a06', title: 'Iceberg of Anger', cat: 'Emotions & Feelings', grades: '7-12', mins: 25, mode: 'Worksheet',
    goal: 'Show that anger often hides other feelings underneath.',
    materials: 'Worksheet',
    steps: ['Draw an iceberg: anger is the tip above water.', 'Brainstorm feelings below the surface: hurt, embarrassed, scared, jealous, tired.', 'Students recall a recent angry moment and write what was really underneath.'],
    debrief: ['If you name the feeling underneath, how might people respond differently?'],
    ws: [
      { t: 'lines', q: 'Above the water: a time I felt angry was...', n: 2 },
      { t: 'check', q: 'Below the water, I might also have felt:', items: ['Hurt', 'Embarrassed', 'Scared', 'Jealous', 'Tired', 'Ignored', 'Disappointed', 'Lonely', 'Guilty', 'Worried'] },
      { t: 'lines', q: 'What I could say next time instead of exploding:', n: 2 },
    ],
  },
  // ---------------- Stress & Anxiety ----------------
  {
    id: 'a07', title: 'Breathing Bubble', cat: 'Stress & Anxiety', grades: '1-12', mins: 5, mode: 'Interactive',
    goal: 'A guided breathing break to calm the nervous system.',
    materials: 'Breathing tool on screen',
    steps: ['Open the Breathing Bubble tool and choose a pattern (box 4-4-4-4 or 4-7-8).', 'Students breathe in as the bubble grows and out as it shrinks.', 'Do 4 rounds, then ask students to rate calmness before and after.'],
    debrief: ['Where could you use this breathing without anyone noticing?'],
    tool: 'breathing',
  },
  {
    id: 'a08', title: '5-4-3-2-1 Grounding', cat: 'Stress & Anxiety', grades: '3-12', mins: 7, mode: 'Interactive',
    goal: 'Use the five senses to come back to the present during anxiety.',
    materials: 'Grounding tool on screen',
    steps: ['Walk through the senses with the tool: 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste.', 'Students say or write their answers.', 'Talk about when to use it (before exams, panic moments).'],
    debrief: ['How did your body feel before and after?'],
    tool: 'grounding',
    ws: [
      { t: 'lines', q: '5 things I can SEE', n: 2 }, { t: 'lines', q: '4 things I can TOUCH', n: 2 },
      { t: 'lines', q: '3 things I can HEAR', n: 1 }, { t: 'lines', q: '2 things I can SMELL', n: 1 }, { t: 'lines', q: '1 thing I can TASTE', n: 1 },
    ],
  },
  {
    id: 'a09', title: 'Worry Sorter: Control Circle', cat: 'Stress & Anxiety', grades: '5-12', mins: 20, mode: 'Interactive',
    goal: 'Separate worries we can act on from those we must let go.',
    materials: 'Worry Sorter tool or worksheet',
    steps: ['Students list current worries on sticky notes (or type in the tool).', 'Sort each into "I can control", "I can influence" or "I cannot control".', 'For controllable ones, write one small action.'],
    debrief: ['What can you do with worries in the "cannot control" circle?'],
    tool: 'worry',
    ws: [
      { t: 'boxes', items: ['I CAN control', 'I can INFLUENCE', 'I CANNOT control'], cols: 3, h: 200 },
      { t: 'lines', q: 'One small step I will take this week:', n: 2 },
    ],
  },
  {
    id: 'a10', title: 'Worry Time Jar', cat: 'Stress & Anxiety', grades: '3-10', mins: 15, mode: 'Worksheet',
    goal: 'Contain worries by scheduling a short daily "worry time".',
    materials: 'Worksheet, a jar or envelope',
    steps: ['Explain that worries can be "parked" and visited later.', 'Students write worries on slips and put them in the jar.', 'They choose a 10-minute worry time each day to open the jar and problem-solve.'],
    debrief: ['Did any worries shrink when you came back to them later?'],
    ws: [
      { t: 'text', v: 'Write each worry on a slip. Put it in your jar. Visit your jar only at your worry time.' },
      { t: 'lines', q: 'My daily worry time is at:', n: 1 },
      { t: 'boxes', items: ['Worry slip', 'Worry slip', 'Worry slip', 'Worry slip', 'Worry slip', 'Worry slip'], cols: 3, h: 80 },
    ],
  },
  {
    id: 'a11', title: 'Exam Stress Toolkit', cat: 'Stress & Anxiety', grades: '8-12', mins: 30, mode: 'Worksheet',
    goal: 'Build a personal plan for exam-time stress.',
    materials: 'Worksheet',
    steps: ['Discuss signs of exam stress (sleep, appetite, irritability).', 'Students rate their current stress.', 'Each fills a toolkit: body, mind, people, study habits.', 'Share one tool per category with the group.'],
    debrief: ['Who is one person you can talk to during exams?'],
    ws: [
      { t: 'scale', q: 'My exam stress right now:', min: 'Relaxed', max: 'Overwhelmed' },
      { t: 'boxes', items: ['BODY: sleep, food, movement', 'MIND: helpful thoughts', 'PEOPLE: who I can talk to', 'STUDY: habits that help'], cols: 2, h: 120 },
      { t: 'lines', q: 'On the morning of the exam I will:', n: 2 },
    ],
  },
  {
    id: 'a12', title: 'Thought Detective', cat: 'Stress & Anxiety', grades: '7-12', mins: 25, mode: 'Worksheet',
    goal: 'Challenge unhelpful thoughts using evidence (CBT skill).',
    materials: 'Worksheet',
    steps: ['Introduce thinking traps: catastrophising, mind-reading, all-or-nothing.', 'Students write a worrying thought.', 'Look for evidence for and against like a detective.', 'Write a balanced thought.'],
    debrief: ['How does the balanced thought change how you feel?'],
    ws: [
      { t: 'lines', q: 'The worrying thought:', n: 2 },
      { t: 'boxes', items: ['Evidence FOR this thought', 'Evidence AGAINST this thought'], cols: 2, h: 150 },
      { t: 'check', q: 'Thinking trap(s) I spotted:', items: ['Catastrophising', 'Mind-reading', 'All-or-nothing', 'Fortune-telling', 'Labelling', 'Should statements'] },
      { t: 'lines', q: 'A more balanced thought:', n: 2 },
    ],
  },
  {
    id: 'a13', title: 'Progressive Muscle Relaxation', cat: 'Mindfulness', grades: '3-12', mins: 10, mode: 'Group',
    goal: 'Release physical tension through tense-and-relax.',
    materials: 'Quiet space, calm voice',
    steps: ['Students sit comfortably and close their eyes.', 'Guide them to squeeze each muscle group for 5 seconds then relax: hands, arms, shoulders, face, stomach, legs, feet.', 'End with three slow breaths.'],
    debrief: ['Which part of your body held the most tension?'],
    tool: 'timer',
  },
  // ---------------- Self-esteem ----------------
  {
    id: 'a14', title: 'Strengths Spotlight', cat: 'Self-Esteem', grades: '5-12', mins: 20, mode: 'Interactive',
    goal: 'Identify personal character strengths.',
    materials: 'Strengths Picker tool or worksheet',
    steps: ['Show the strengths cards (kindness, curiosity, courage, humour...).', 'Students pick their top 5.', 'Write a real example for each.', 'Partners add one strength they see in each other.'],
    debrief: ['How can you use a top strength in a hard situation this week?'],
    tool: 'strengths',
    ws: [
      { t: 'table', cols: ['My strength', 'A time I used it'], rows: 5 },
      { t: 'lines', q: 'A strength my friend sees in me:', n: 1 },
    ],
  },
  {
    id: 'a15', title: 'Me Tree', cat: 'Self-Esteem', grades: '3-10', mins: 25, mode: 'Worksheet',
    goal: 'Reflect on roots (values, family), trunk (strengths) and fruits (achievements).',
    materials: 'Worksheet, colours',
    steps: ['Draw a tree with roots, trunk, branches and fruits.', 'Roots: people and values that support me. Trunk: my strengths. Branches: hopes. Fruits: things I am proud of.', 'Display trees in a "forest" if students agree.'],
    debrief: ['Which part of your tree was easiest or hardest to fill?'],
    ws: [{ t: 'draw', q: 'Draw your tree. Label roots, trunk, branches and fruits.', h: 420 }],
  },
  {
    id: 'a16', title: 'Compliment Shower', cat: 'Self-Esteem', grades: '3-12', mins: 15, mode: 'Group',
    goal: 'Practise giving and receiving genuine compliments.',
    materials: 'Paper sheets taped on backs, markers',
    steps: ['Each student has a sheet on their back.', 'Classmates write specific, kind compliments (no appearance-only comments).', 'Students read their sheet quietly and pick their favourite.'],
    debrief: ['How did it feel to receive? Was it harder to give or receive?'],
  },
  {
    id: 'a17', title: 'Inner Critic vs Inner Coach', cat: 'Self-Esteem', grades: '7-12', mins: 20, mode: 'Worksheet',
    goal: 'Replace harsh self-talk with supportive self-talk.',
    materials: 'Worksheet',
    steps: ['Students write 3 things their inner critic says.', 'Ask: "Would you say this to a best friend?"', 'Rewrite each as a kind but honest coach would.'],
    debrief: ['Which coach statement will you practise this week?'],
    ws: [{ t: 'table', cols: ['My inner CRITIC says...', 'My inner COACH says...'], rows: 4 }],
  },
  {
    id: 'a18', title: 'Proud Moments Timeline', cat: 'Self-Esteem', grades: '5-12', mins: 20, mode: 'Worksheet',
    goal: 'Recall achievements and resilience across life so far.',
    materials: 'Worksheet',
    steps: ['Draw a line from birth to today.', 'Mark at least 5 proud moments, including times they overcame difficulty.', 'Share one with a partner.'],
    debrief: ['What do your proud moments say about who you are?'],
    ws: [
      { t: 'draw', q: 'My timeline (mark 5 proud moments):', h: 160 },
      { t: 'lines', q: 'A challenge I overcame and what helped me:', n: 3 },
    ],
  },
  // ---------------- Friendships & Peers ----------------
  {
    id: 'a19', title: 'Friendship Recipe', cat: 'Friendships & Peers', grades: '3-9', mins: 20, mode: 'Worksheet',
    goal: 'Identify qualities of a healthy friendship.',
    materials: 'Worksheet',
    steps: ['Students write a recipe for a good friend: ingredients (qualities) and method (actions).', 'Compare recipes in groups and build a class recipe.'],
    debrief: ['Which ingredient do you bring to your friendships?'],
    ws: [
      { t: 'lines', q: 'Ingredients (qualities of a good friend):', n: 4 },
      { t: 'lines', q: 'Method (things good friends do):', n: 4 },
      { t: 'lines', q: 'Ingredient I bring:', n: 1 },
    ],
  },
  {
    id: 'a20', title: 'Healthy or Unhealthy?', cat: 'Friendships & Peers', grades: '6-12', mins: 25, mode: 'Interactive',
    goal: 'Recognise healthy, unhealthy and pressuring friendship behaviours.',
    materials: 'Scenario Cards tool (Friendships deck)',
    steps: ['Read a scenario card aloud.', 'Students vote: healthy, unhealthy, or it depends.', 'Discuss what a respectful response would be.'],
    debrief: ['What are signs a friendship needs a boundary?'],
    tool: 'scenarios',
  },
  {
    id: 'a21', title: 'Peer Pressure Role Play', cat: 'Friendships & Peers', grades: '6-12', mins: 30, mode: 'Group',
    goal: 'Practise refusal skills: say no, give a reason, suggest another plan, walk away.',
    materials: 'Scenario Cards tool (Peer pressure deck)',
    steps: ['Teach the 4-step refusal skill.', 'In threes, one applies pressure, one refuses, one observes.', 'Rotate roles and give feedback on tone and body language.'],
    debrief: ['Which refusal line felt most natural for you?'],
    tool: 'scenarios',
    ws: [
      { t: 'lines', q: 'A pressure situation I might face:', n: 2 },
      { t: 'boxes', items: ['1. Say NO clearly', '2. Give a reason', '3. Suggest another plan', '4. Walk away / get help'], cols: 2, h: 90 },
    ],
  },
  {
    id: 'a22', title: 'Two Truths and a Wish', cat: 'Icebreakers & Team', grades: '3-12', mins: 15, mode: 'Group',
    goal: 'Build connection and learn about classmates.',
    materials: 'None',
    steps: ['Each student shares two true facts about themselves and one wish.', 'The group guesses which is the wish.', 'Follow up: how could we help each other with our wishes?'],
    debrief: ['What surprised you about a classmate?'],
  },
  {
    id: 'a23', title: 'Question Spinner Circle', cat: 'Icebreakers & Team', grades: '3-12', mins: 15, mode: 'Interactive',
    goal: 'Warm up a group with fun, safe discussion questions.',
    materials: 'Question Spinner tool',
    steps: ['Choose a deck (icebreaker, reflection, career, feelings).', 'Spin and the student whose turn it is answers (pass is allowed).', 'Keep it light; thank each speaker.'],
    debrief: ['Which question would you like to ask the group?'],
    tool: 'spinner',
  },
  {
    id: 'a24', title: 'Human Knot', cat: 'Icebreakers & Team', grades: '5-12', mins: 15, mode: 'Group',
    goal: 'Teamwork, communication and patience.',
    materials: 'Open space, groups of 8-10',
    steps: ['Students stand in a circle and grab two different hands across the circle.', 'Without letting go, they untangle into one circle.', 'Debrief about communication and leadership.'],
    debrief: ['Who led? How did you handle frustration?'],
    tool: 'timer',
  },
  // ---------------- Bullying & Safety ----------------
  {
    id: 'a25', title: 'Upstander Pledge', cat: 'Bullying & Safety', grades: '4-12', mins: 25, mode: 'Worksheet',
    goal: 'Move from bystander to upstander with safe actions.',
    materials: 'Worksheet',
    steps: ['Define bully, target, bystander, upstander.', 'Brainstorm safe upstander actions (tell an adult, include, distract, support afterwards).', 'Students write a personal pledge.'],
    debrief: ['What makes it hard to be an upstander, and what would help?'],
    ws: [
      { t: 'check', q: 'Safe things I can do when I see bullying:', items: ['Tell a trusted adult', 'Invite the person to join me', 'Change the subject / distract', 'Check on them afterwards', 'Not share hurtful posts', 'Report online bullying'] },
      { t: 'lines', q: 'My upstander pledge:', n: 3 },
      { t: 'lines', q: 'Trusted adults in school I can tell:', n: 2 },
    ],
  },
  {
    id: 'a26', title: 'Crumpled Heart', cat: 'Bullying & Safety', grades: '3-9', mins: 15, mode: 'Group',
    goal: 'Show that hurtful words leave lasting marks.',
    materials: 'A paper heart',
    steps: ['Pass around a paper heart; each student says a hurtful phrase and crumples it a little.', 'Then each says an apology and tries to smooth it.', 'Notice the creases that stay.'],
    debrief: ['What does this teach us about words? What can we do instead?'],
  },
  {
    id: 'a27', title: 'Safe Circle Map', cat: 'Bullying & Safety', grades: '3-10', mins: 20, mode: 'Worksheet',
    goal: 'Identify trusted people and safe places.',
    materials: 'Worksheet',
    steps: ['Draw circles: me, family, friends, school adults, community helpers.', 'Write names in each circle.', 'Add helpline numbers the school recommends.'],
    debrief: ['Who would you go to first if something felt unsafe?'],
    ws: [
      { t: 'boxes', items: ['Family I trust', 'Friends I trust', 'Adults in school', 'Community / helplines'], cols: 2, h: 130 },
      { t: 'lines', q: 'Safe places I can go:', n: 2 },
    ],
  },
  // ---------------- Conflict Resolution ----------------
  {
    id: 'a28', title: 'I-Statement Builder', cat: 'Conflict Resolution', grades: '4-12', mins: 20, mode: 'Worksheet',
    goal: 'Express feelings without blaming using "I feel... when... because... I need...".',
    materials: 'Worksheet',
    steps: ['Contrast "You always ruin it!" with an I-statement.', 'Students convert 3 blaming sentences into I-statements.', 'Practise saying them aloud in pairs.'],
    debrief: ['How might the other person react differently?'],
    ws: [
      { t: 'text', v: 'Formula: I feel ______ when ______ because ______. I need ______.' },
      { t: 'table', cols: ['Blaming sentence', 'My I-statement'], rows: 3 },
    ],
  },
  {
    id: 'a29', title: 'Conflict Escalator', cat: 'Conflict Resolution', grades: '6-12', mins: 25, mode: 'Worksheet',
    goal: 'See how conflicts escalate step by step and where to step off.',
    materials: 'Worksheet',
    steps: ['Draw an escalator with 5 steps from disagreement to blow-up.', 'Fill in a real or sample conflict step by step.', 'Mark where someone could have stepped off and how.'],
    debrief: ['What is your personal "step off" signal?'],
    ws: [
      { t: 'table', cols: ['Step', 'What happened / was said', 'How to step off here'], rows: 5 },
    ],
  },
  {
    id: 'a30', title: 'Win-Win Problem Solving', cat: 'Conflict Resolution', grades: '5-12', mins: 25, mode: 'Interactive',
    goal: 'Use a structured method to solve a disagreement.',
    materials: 'Scenario Cards tool (Conflict deck), worksheet',
    steps: ['Pick a conflict scenario.', 'Step 1 define the problem, 2 brainstorm solutions, 3 evaluate, 4 choose, 5 check later.', 'Groups present their win-win solution.'],
    debrief: ['Was there a solution where both sides got something?'],
    tool: 'scenarios',
    ws: [
      { t: 'lines', q: '1. The problem is:', n: 2 },
      { t: 'lines', q: '2. Possible solutions:', n: 3 },
      { t: 'table', cols: ['Solution', 'Good for me?', 'Good for them?'], rows: 3 },
      { t: 'lines', q: '4. We chose:', n: 1 },
    ],
  },
  // ---------------- Study Skills & Exams ----------------
  {
    id: 'a31', title: 'Weekly Study Planner', cat: 'Study Skills & Exams', grades: '6-12', mins: 25, mode: 'Worksheet',
    goal: 'Plan study time realistically with breaks.',
    materials: 'Worksheet',
    steps: ['Students block fixed commitments first (school, tuition, meals, sleep).', 'Add 25-minute study blocks with 5-minute breaks.', 'Include fun and rest time.'],
    debrief: ['What is the biggest time-waster you can reduce?'],
    ws: [{ t: 'table', cols: ['Day', 'Morning', 'Afternoon', 'Evening', 'Rest / fun'], rows: 7 }],
  },
  {
    id: 'a32', title: 'Pomodoro Power Hour', cat: 'Study Skills & Exams', grades: '6-12', mins: 30, mode: 'Interactive',
    goal: 'Experience focused work sprints with planned breaks.',
    materials: 'Timer tool',
    steps: ['Set the timer to 25 minutes of focused work; phones away.', 'Take a 5-minute movement break.', 'Reflect on focus level before and after.'],
    debrief: ['How many tasks did you finish compared to usual?'],
    tool: 'timer',
  },
  {
    id: 'a33', title: 'Learning Style Discovery', cat: 'Study Skills & Exams', grades: '6-12', mins: 20, mode: 'Worksheet',
    goal: 'Explore study methods that suit each student.',
    materials: 'Worksheet',
    steps: ['Students tick study methods they enjoy.', 'Group into visual, auditory, hands-on, reading/writing tendencies.', 'Each chooses 2 new methods to try.'],
    debrief: ['Remember: everyone uses a mix. Which new method will you try?'],
    ws: [
      { t: 'check', q: 'I remember best when I...', items: ['Draw mind maps or diagrams', 'Explain it aloud to someone', 'Use flashcards', 'Write summaries', 'Watch a video', 'Build or act it out', 'Record and listen', 'Solve practice questions'] },
      { t: 'lines', q: 'Two methods I will try this week:', n: 2 },
    ],
  },
  {
    id: 'a34', title: 'Exam Day Countdown Plan', cat: 'Study Skills & Exams', grades: '8-12', mins: 20, mode: 'Worksheet',
    goal: 'Prepare a calm plan for the week before and the day of the exam.',
    materials: 'Worksheet',
    steps: ['Fill in revision targets for each of the last 7 days.', 'Write a night-before checklist and morning routine.', 'Add a calming phrase for the exam hall.'],
    debrief: ['What will you do if your mind goes blank?'],
    ws: [
      { t: 'table', cols: ['Day before exam', 'Topics to revise', 'Done?'], rows: 7 },
      { t: 'check', q: 'Night-before checklist:', items: ['Admit card / ID', 'Pens, pencils, geometry box', 'Water bottle', 'Uniform ready', 'Sleep by 10 pm', 'Alarm set'] },
      { t: 'lines', q: 'My calming phrase:', n: 1 },
    ],
  },
  // ---------------- Career Exploration ----------------
  {
    id: 'a35', title: 'Career Interest Explorer (RIASEC)', cat: 'Career Exploration', grades: '8-12', mins: 30, mode: 'Worksheet',
    goal: 'Identify interest types: Realistic, Investigative, Artistic, Social, Enterprising, Conventional.',
    materials: 'Worksheet',
    steps: ['Students tick activities they enjoy in each category.', 'Count ticks and find their top 2 letters.', 'Explore careers matching their code.'],
    debrief: ['Did your result match what you expected? Why or why not?'],
    ws: [
      { t: 'check', q: 'R - Realistic (hands-on):', items: ['Fixing things', 'Outdoor work', 'Using tools/machines'] },
      { t: 'check', q: 'I - Investigative (thinking):', items: ['Solving puzzles', 'Science experiments', 'Researching'] },
      { t: 'check', q: 'A - Artistic (creating):', items: ['Drawing / design', 'Music / drama', 'Writing stories'] },
      { t: 'check', q: 'S - Social (helping):', items: ['Teaching others', 'Listening to friends', 'Volunteering'] },
      { t: 'check', q: 'E - Enterprising (leading):', items: ['Leading a team', 'Selling / persuading', 'Starting projects'] },
      { t: 'check', q: 'C - Conventional (organising):', items: ['Keeping records', 'Planning schedules', 'Working with numbers'] },
      { t: 'lines', q: 'My top two letters and three careers to explore:', n: 2 },
    ],
  },
  {
    id: 'a36', title: 'Career Interview Project', cat: 'Career Exploration', grades: '8-12', mins: 40, mode: 'Worksheet',
    goal: 'Learn about a real job by interviewing someone.',
    materials: 'Worksheet',
    steps: ['Students choose a person whose work interests them.', 'Prepare questions in class.', 'Conduct the interview at home and present findings.'],
    debrief: ['What surprised you about the job?'],
    ws: [
      { t: 'lines', q: 'Person and job:', n: 1 },
      { t: 'lines', q: 'What does a typical day look like?', n: 3 },
      { t: 'lines', q: 'What subjects or skills are important?', n: 3 },
      { t: 'lines', q: 'What do you enjoy most and least?', n: 3 },
      { t: 'lines', q: 'Advice for a student like me:', n: 3 },
    ],
  },
  {
    id: 'a37', title: 'Future Me Letter', cat: 'Career Exploration', grades: '7-12', mins: 25, mode: 'Worksheet',
    goal: 'Imagine a positive future self and the steps to get there.',
    materials: 'Worksheet, envelope',
    steps: ['Students write a letter from themselves 10 years in the future.', 'Include what they do, what they value and advice to their current self.', 'Seal it; return it at year-end.'],
    debrief: ['What is one step "future you" wants you to take now?'],
    ws: [{ t: 'text', v: 'Dear me (from 10 years in the future)...' }, { t: 'lines', q: '', n: 16 }],
  },
  {
    id: 'a38', title: 'Stream & Subject Decision Grid', cat: 'Career Exploration', grades: '9-11', mins: 30, mode: 'Worksheet',
    goal: 'Make an informed choice of stream/subjects using interests, abilities and goals.',
    materials: 'Worksheet, recent marks',
    steps: ['List options (Science, Commerce, Humanities, vocational).', 'Score each from 1-5 for interest, ability, career fit and personal choice.', 'Discuss results with parents and counsellor.'],
    debrief: ['Is the decision yours? Who else has influenced it?'],
    ws: [
      { t: 'table', cols: ['Option', 'Interest (1-5)', 'Ability (1-5)', 'Career fit (1-5)', 'My choice (1-5)', 'Total'], rows: 4 },
      { t: 'lines', q: 'Questions I still need answered:', n: 3 },
    ],
  },
  // ---------------- Goal Setting ----------------
  {
    id: 'a39', title: 'SMART Goal Ladder', cat: 'Goal Setting', grades: '6-12', mins: 25, mode: 'Worksheet',
    goal: 'Turn a big wish into a SMART goal with small steps.',
    materials: 'Worksheet',
    steps: ['Explain SMART: Specific, Measurable, Achievable, Relevant, Time-bound.', 'Students write a goal and test it against SMART.', 'Break it into 5 ladder rungs.'],
    debrief: ['What is the very first rung you can do this week?'],
    ws: [
      { t: 'lines', q: 'My goal:', n: 2 },
      { t: 'table', cols: ['S', 'M', 'A', 'R', 'T'], rows: 1 },
      { t: 'table', cols: ['Rung (step)', 'By when', 'Done?'], rows: 5 },
    ],
  },
  {
    id: 'a40', title: 'Vision Board', cat: 'Goal Setting', grades: '5-12', mins: 40, mode: 'Group',
    goal: 'Visualise hopes in areas of life: school, health, friends, family, fun.',
    materials: 'Old magazines, chart paper, glue (or drawing)',
    steps: ['Divide the board into 5 life areas.', 'Students add pictures/words for each.', 'Gallery walk and short sharing.'],
    debrief: ['Which area matters most to you right now?'],
    ws: [{ t: 'boxes', items: ['School', 'Health', 'Friends', 'Family', 'Fun & hobbies', 'Who I want to be'], cols: 3, h: 160 }],
  },
  {
    id: 'a41', title: 'Habit Tracker Challenge', cat: 'Goal Setting', grades: '5-12', mins: 15, mode: 'Worksheet',
    goal: 'Build a positive habit over 3 weeks.',
    materials: 'Worksheet',
    steps: ['Choose one small daily habit (drink water, 10 min reading, sleep on time).', 'Tick each day it is done.', 'Review in 3 weeks with the counsellor.'],
    debrief: ['What made it easier on the days you succeeded?'],
    ws: [
      { t: 'lines', q: 'My habit:', n: 1 },
      { t: 'table', cols: ['Week', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], rows: 3 },
      { t: 'lines', q: 'My reward when I finish:', n: 1 },
    ],
  },
  // ---------------- Mindfulness ----------------
  {
    id: 'a42', title: 'Mindful Raisin (or Chocolate) Tasting', cat: 'Mindfulness', grades: '3-12', mins: 10, mode: 'Group',
    goal: 'Experience slowing down and paying full attention.',
    materials: 'One raisin or small sweet per student (check allergies)',
    steps: ['Look at it as if seeing it for the first time.', 'Notice texture, smell, sound when squeezed.', 'Place on tongue without chewing; then chew slowly.', 'Share observations.'],
    debrief: ['What do we miss when we rush through things?'],
  },
  {
    id: 'a43', title: 'Gratitude Journal Page', cat: 'Mindfulness', grades: '3-12', mins: 10, mode: 'Worksheet',
    goal: 'Train attention toward positive moments.',
    materials: 'Worksheet',
    steps: ['Students write 3 good things from today, however small.', 'Write why each happened.', 'Repeat daily for a week.'],
    debrief: ['Did noticing good things change your mood?'],
    ws: [
      { t: 'table', cols: ['Good thing', 'Why it happened / who helped'], rows: 3 },
      { t: 'lines', q: 'Someone I want to thank:', n: 1 },
      { t: 'faces', q: 'Circle how I feel after writing this:' },
    ],
  },
  {
    id: 'a44', title: 'Calm-Down Corner Menu', cat: 'Mindfulness', grades: '1-8', mins: 20, mode: 'Worksheet',
    goal: 'Create a personal menu of calming choices.',
    materials: 'Worksheet, colours',
    steps: ['Brainstorm calming activities (breathing, drawing, water, stretching).', 'Students design a "menu" with starters, mains and desserts.', 'Keep it in their diary.'],
    debrief: ['Which item works fastest for you?'],
    ws: [{ t: 'boxes', items: ['Quick starters (1 minute)', 'Main course (5 minutes)', 'Dessert (something I enjoy)'], cols: 3, h: 180 }],
  },
  // ---------------- Family ----------------
  {
    id: 'a45', title: 'Family Circles', cat: 'Family', grades: '4-12', mins: 20, mode: 'Worksheet',
    goal: 'Map family relationships and support (sensitive: allow privacy).',
    materials: 'Worksheet',
    steps: ['Students draw themselves in the centre.', 'Place family members closer or farther depending on how close they feel.', 'Optional private reflection on one relationship to strengthen.'],
    debrief: ['(Privately) Which relationship would you like to feel closer?'],
    ws: [{ t: 'draw', q: 'Put yourself in the middle. Draw family members near or far.', h: 340 }, { t: 'lines', q: 'One small thing I could do to feel closer to someone:', n: 2 }],
  },
  {
    id: 'a46', title: 'Changes at Home Storybook', cat: 'Family', grades: '2-8', mins: 30, mode: 'Worksheet',
    goal: 'Help a student process change (new sibling, moving, separation, loss).',
    materials: 'Worksheet (best used individually)',
    steps: ['Student draws "before", "the change", and "now".', 'Talk about feelings in each picture.', 'Finish with "Things that stay the same" and "People who help me".'],
    debrief: ['What helps you most when things change?'],
    ws: [
      { t: 'boxes', items: ['Before', 'The change', 'Now'], cols: 3, h: 170 },
      { t: 'lines', q: 'Things that stay the same:', n: 2 },
      { t: 'lines', q: 'People who help me:', n: 2 },
    ],
  },
  // ---------------- Digital Wellbeing ----------------
  {
    id: 'a47', title: 'Screen Time Audit', cat: 'Digital Wellbeing', grades: '6-12', mins: 20, mode: 'Worksheet',
    goal: 'Reflect on device use and its effect on mood and sleep.',
    materials: 'Worksheet',
    steps: ['Students estimate daily time on each app/activity.', 'Mark how each makes them feel (better / same / worse).', 'Set one healthy limit.'],
    debrief: ['Which app leaves you feeling worse? What could replace it?'],
    ws: [
      { t: 'table', cols: ['App / activity', 'Time per day', 'Feel better / same / worse'], rows: 6 },
      { t: 'lines', q: 'My healthy limit:', n: 1 },
      { t: 'lines', q: 'What I will do instead:', n: 2 },
    ],
  },
  {
    id: 'a48', title: 'Think Before You Post', cat: 'Digital Wellbeing', grades: '6-12', mins: 20, mode: 'Interactive',
    goal: 'Use the THINK test (True, Helpful, Inspiring, Necessary, Kind) for online posts.',
    materials: 'Scenario Cards tool (Online deck)',
    steps: ['Read a sample post or online situation.', 'Run it through THINK as a class.', 'Rewrite posts that fail.'],
    debrief: ['What could be the long-term effect of a careless post?'],
    tool: 'scenarios',
    ws: [{ t: 'table', cols: ['Post', 'T', 'H', 'I', 'N', 'K', 'Post it?'], rows: 4 }],
  },
  {
    id: 'a49', title: 'Sleep Hygiene Detective', cat: 'Digital Wellbeing', grades: '6-12', mins: 15, mode: 'Worksheet',
    goal: 'Improve sleep habits linked to mood and concentration.',
    materials: 'Worksheet',
    steps: ['Students track bedtime, wake time and pre-sleep habits for a week.', 'Spot patterns (screens, caffeine, late study).', 'Choose one change.'],
    debrief: ['How did your mood change on better-sleep days?'],
    ws: [{ t: 'table', cols: ['Day', 'Bedtime', 'Wake time', 'Screen before bed?', 'Mood next day (1-5)'], rows: 7 }],
  },
  {
    id: 'a50', title: 'Kindness Bingo', cat: 'Icebreakers & Team', grades: '3-12', mins: 15, mode: 'Worksheet',
    goal: 'Encourage acts of kindness over a week.',
    materials: 'Worksheet',
    steps: ['Each square is an act of kindness.', 'Students cross off squares during the week.', 'Celebrate a full line or full card.'],
    debrief: ['Which act of kindness made the biggest difference?'],
    ws: [{ t: 'boxes', items: ['Hold the door', 'Compliment a classmate', 'Help at home', 'Include someone new', 'Thank a teacher', 'Share something', 'Pick up litter', 'Smile at 5 people', 'FREE: your idea', 'Write a kind note', 'Help with homework', 'Listen without interrupting', 'Say sorry', 'Water a plant', 'Cheer someone up', 'Thank a helper staff'], cols: 4, h: 90 }],
  },
  // ---------------- Art Therapy ----------------
  {
    id: 'a51', title: 'Mandala of Me', cat: 'Art Therapy', grades: '3-12', mins: 25, mode: 'Interactive',
    goal: 'Calm the mind through repetitive, symmetrical drawing and express identity through colour and pattern.',
    materials: 'Mandala Maker tool, or worksheet and colours',
    steps: ['Explain that a mandala is a circle that grows from the centre outward.', 'Start in the middle with something that represents "me" (a shape, symbol or colour).', 'Add rings outward: family, friends, hobbies, hopes.', 'Work slowly and quietly; soft music helps.', 'Share the colours chosen and what they mean.'],
    debrief: ['How did your body feel while drawing?', 'Which ring was easiest to fill? Which was hardest?'],
    tool: 'mandala',
    ws: [{ t: 'text', v: 'Start in the centre with something that is "you". Add a ring for family, then friends, then hobbies, then hopes.' }, { t: 'draw', q: 'My mandala:', h: 470 }, { t: 'lines', q: 'The colours I chose mean:', n: 2 }],
  },
  {
    id: 'a52', title: 'Inside / Outside Mask', cat: 'Art Therapy', grades: '6-12', mins: 35, mode: 'Worksheet',
    goal: 'Explore the difference between what we show others and what we feel inside.',
    materials: 'Worksheet (or paper plate masks), colours, magazines',
    steps: ['Outside of the mask: show what others see (how you act, what you show).', 'Inside of the mask: show feelings and thoughts you keep hidden.', 'Use colours, words, symbols or pictures.', 'Only share what you feel comfortable sharing.'],
    debrief: ['Who gets to see the inside of your mask?', 'What would make it safer to show more of the inside?'],
    tool: 'studio', toolArg: 'mask',
    ws: [{ t: 'boxes', items: ['OUTSIDE: what others see', 'INSIDE: what I keep inside'], cols: 2, h: 340 }, { t: 'lines', q: 'One person I can show my "inside" to:', n: 1 }],
  },
  {
    id: 'a53', title: 'Draw Your Worry Monster', cat: 'Art Therapy', grades: '2-9', mins: 25, mode: 'Worksheet',
    goal: 'Externalise worries by turning them into a silly creature that can be shrunk.',
    materials: 'Worksheet, colours',
    steps: ['Draw your worry as a monster. What colour is it? How big?', 'Give it a funny name.', 'Write what the monster whispers to you.', 'Draw yourself with a "shrinking tool" (a friend, breathing, a brave thought).', 'Optionally scrunch up or post the monster in a "worry box".'],
    debrief: ['What makes your worry monster smaller?', 'Who can help you shrink it?'],
    tool: 'studio', toolArg: 'monster',
    ws: [{ t: 'draw', q: 'My worry monster:', h: 300 }, { t: 'lines', q: 'Its name is:', n: 1 }, { t: 'lines', q: 'It whispers:', n: 2 }, { t: 'lines', q: 'What shrinks it:', n: 2 }],
  },
  {
    id: 'a54', title: 'Inner Weather Report', cat: 'Art Therapy', grades: '1-10', mins: 15, mode: 'Worksheet',
    goal: 'Use weather as a metaphor to express mood without needing feeling words.',
    materials: 'Worksheet or Art Studio (weather template)',
    steps: ['Ask: "If your feelings today were weather, what would it be?"', 'Draw the weather in the window: sun, clouds, storm, fog, rainbow…', 'Add a forecast: what might change the weather later?', 'Students present their "weather report" like a TV presenter (optional).'],
    debrief: ['What helps your storms pass?', 'Can sunshine and clouds be there at the same time?'],
    tool: 'studio', toolArg: 'weather',
    ws: [{ t: 'draw', q: 'The weather inside me today:', h: 320 }, { t: 'lines', q: 'Forecast – what could change my weather:', n: 2 }],
  },
  {
    id: 'a55', title: 'My Safe Place', cat: 'Art Therapy', grades: '2-12', mins: 25, mode: 'Worksheet',
    goal: 'Create a mental image of safety and calm that can be recalled when anxious.',
    materials: 'Worksheet, colours; calm music',
    steps: ['Guide a short relaxation: eyes closed, imagine a place where you feel completely safe.', 'Notice what you see, hear, smell and feel there.', 'Draw the place with as much detail as possible.', 'Add one word that describes how it feels.'],
    debrief: ['When could you visit your safe place in your mind?'],
    tool: 'studio', toolArg: 'safe',
    ws: [{ t: 'draw', q: 'My safe place:', h: 360 }, { t: 'table', cols: ['I see', 'I hear', 'I smell', 'I feel'], rows: 2 }],
  },
  {
    id: 'a56', title: 'Scribble Chase', cat: 'Art Therapy', grades: '1-10', mins: 15, mode: 'Interactive',
    goal: 'Release tension and spark creativity with free scribbling, then find pictures in it.',
    materials: 'Art Studio (blank) or paper and crayons',
    steps: ['With eyes closed (or fast), scribble all over the page for 30 seconds.', 'Open your eyes and turn the page around. What shapes or creatures can you see?', 'Colour in the shapes you found to make a picture.', 'Give the picture a title.'],
    debrief: ['How did it feel to scribble without rules?', 'What did you find hidden in your scribble?'],
    tool: 'studio', toolArg: 'blank',
    ws: [{ t: 'draw', q: 'Scribble here, then find and colour the hidden pictures:', h: 450 }, { t: 'lines', q: 'Title of my picture:', n: 1 }],
  },
  {
    id: 'a57', title: 'Heart Map', cat: 'Art Therapy', grades: '3-12', mins: 25, mode: 'Worksheet',
    goal: 'Identify the people, places, memories and values that matter most.',
    materials: 'Worksheet or Art Studio (heart template)',
    steps: ['Divide the heart into sections of different sizes.', 'Bigger sections = things that matter more.', 'Fill each section with drawings, words or colours.', 'Share one section with a partner.'],
    debrief: ['What surprised you about what takes up the most space?'],
    tool: 'studio', toolArg: 'heart',
    ws: [{ t: 'draw', q: 'Divide and fill your heart:', h: 420 }, { t: 'lines', q: 'The biggest part of my heart is:', n: 1 }],
  },
  {
    id: 'a58', title: 'Bridge Drawing', cat: 'Art Therapy', grades: '6-12', mins: 30, mode: 'Worksheet',
    goal: 'Visualise the journey from a current difficulty to a hoped-for future, and the supports needed.',
    materials: 'Worksheet or Art Studio (bridge template)',
    steps: ['On the left, draw where you are now (a feeling, a situation).', 'On the right, draw where you want to be.', 'Draw a bridge between them. What is it made of? Is it strong or shaky?', 'Add the people and strengths that help you cross. Mark yourself on the bridge.'],
    debrief: ['Where are you on the bridge today?', 'What would make the bridge stronger?'],
    tool: 'studio', toolArg: 'bridge',
    ws: [{ t: 'draw', q: 'Where I am  →  my bridge  →  where I want to be', h: 320 }, { t: 'lines', q: 'What helps me cross:', n: 3 }],
  },
  {
    id: 'a59', title: 'Feelings Jar', cat: 'Art Therapy', grades: '1-10', mins: 15, mode: 'Interactive',
    goal: 'Show the mix and amount of feelings in a visual way.',
    materials: 'Art Studio (jar template) or worksheet with colours',
    steps: ['Choose a colour for each feeling (make a key).', 'Fill the jar with layers – the more you feel it, the thicker the layer.', 'Talk about which feeling takes up most of the jar.', 'Optional: draw what you would like the jar to look like next week.'],
    debrief: ['Which layer would you like to make smaller or bigger?'],
    tool: 'studio', toolArg: 'jar',
    ws: [{ t: 'table', cols: ['Colour', 'Feeling'], rows: 5 }, { t: 'boxes', items: ['My feelings jar today', 'My jar next week (hope)'], cols: 2, h: 300 }],
  },
  {
    id: 'a60', title: 'Comic Strip Problem Solver', cat: 'Art Therapy', grades: '5-12', mins: 35, mode: 'Worksheet',
    goal: 'Retell a problem as a comic and practise imagining a positive ending.',
    materials: 'Worksheet or Art Studio (comic template)',
    steps: ['Choose a real or made-up problem.', 'Panel 1-2: the problem and how the character felt.', 'Panel 3-4: what they tried.', 'Panel 5-6: what helped and the happy (or better) ending.', 'Use speech bubbles and thought bubbles.'],
    debrief: ['Could the solution in your comic work in real life?'],
    tool: 'studio', toolArg: 'comic',
    ws: [{ t: 'boxes', items: ['1. The problem', '2. How I felt', '3. What I tried', '4. What happened', '5. What helped', '6. The ending'], cols: 3, h: 200 }],
  },
];

/* Question decks for the spinner, and scenario cards */
window.SPINNER_DECKS = {
  'Icebreakers': ['If you could have any superpower, what would it be?', 'What is your favourite comfort food?', 'Describe your perfect weekend.', 'Which animal are you most like and why?', 'What song always cheers you up?', 'If you could visit any place, where?', 'What is a hobby you would love to try?', 'Who is someone you admire?', 'What makes you laugh the most?', 'What is something you are good at that people might not know?'],
  'Feelings': ['Happy', 'Sad', 'Angry', 'Nervous', 'Excited', 'Lonely', 'Proud', 'Embarrassed', 'Jealous', 'Calm', 'Frustrated', 'Hopeful'],
  'Reflection': ['What was the best part of your week?', 'What is something difficult you handled well?', 'What is one thing you want to get better at?', 'When did you last help someone?', 'What does a good friend do?', 'What helps you calm down?', 'What are you grateful for today?', 'What would you tell a younger student starting at this school?'],
  'Career': ['What job would you do for free?', 'Which school subject do you enjoy most?', 'Would you like to work indoors or outdoors?', 'Do you prefer working alone or in a team?', 'Name a job that helps people.', 'What problem in the world would you like to solve?', 'Who in your family has an interesting job?', 'What skill do you want to learn by age 20?'],
};

window.SCENARIO_DECKS = {
  'Friendships': [
    'Your friend gets upset whenever you sit with other people at lunch.',
    'A friend always copies your homework and says "that is what friends do".',
    'Your friend listens to you and keeps your secrets, unless you are in danger.',
    'Your group makes fun of a classmate in a chat and expects you to add something.',
    'A friend forgets your birthday but apologises sincerely the next day.',
    'A friend asks for your password "just to check something".',
  ],
  'Peer pressure': [
    'Older students offer you a cigarette/vape behind the school building.',
    'Your friends are planning to skip a class and want you to come.',
    'Someone dares you to post an embarrassing photo of a classmate.',
    'Friends pressure you to buy expensive shoes so you "fit in".',
    'A group asks you to lie to a teacher to cover for them.',
  ],
  'Conflict': [
    'Two friends both want to be captain of the team.',
    'Your sibling keeps using your things without asking.',
    'A group project partner is not doing their share.',
    'Someone bumped into you and you think it was deliberate.',
    'Your parents and you disagree on how much screen time is okay.',
  ],
  'Online': [
    'You see a mean meme about a classmate being shared widely.',
    'A stranger online asks for your school name and photos.',
    'You are angry with a friend and want to post about it.',
    'You are added to a group chat that spreads rumours.',
    'A post claims a shocking "fact" with no source.',
  ],
};

window.STRENGTHS = ['Kindness', 'Curiosity', 'Courage', 'Honesty', 'Humour', 'Creativity', 'Fairness', 'Leadership', 'Teamwork', 'Perseverance', 'Gratitude', 'Hope', 'Self-control', 'Love of learning', 'Forgiveness', 'Humility', 'Bravery', 'Patience', 'Empathy', 'Responsibility', 'Organisation', 'Enthusiasm', 'Wisdom', 'Appreciation of beauty'];

window.FEELINGS_WHEEL = [
  { core: 'Happy', words: ['Joyful', 'Proud', 'Content', 'Excited', 'Grateful', 'Hopeful', 'Playful', 'Confident'] },
  { core: 'Sad', words: ['Lonely', 'Hurt', 'Disappointed', 'Guilty', 'Hopeless', 'Left out', 'Grieving', 'Low'] },
  { core: 'Angry', words: ['Frustrated', 'Irritated', 'Jealous', 'Annoyed', 'Betrayed', 'Furious', 'Resentful', 'Disrespected'] },
  { core: 'Scared', words: ['Anxious', 'Nervous', 'Worried', 'Insecure', 'Overwhelmed', 'Panicked', 'Helpless', 'Rejected'] },
  { core: 'Surprised', words: ['Amazed', 'Confused', 'Shocked', 'Startled', 'Curious', 'Speechless', 'Eager', 'Moved'] },
  { core: 'Disgusted', words: ['Embarrassed', 'Uncomfortable', 'Disapproving', 'Repelled', 'Awful', 'Ashamed', 'Judged', 'Offended'] },
  { core: 'Calm', words: ['Peaceful', 'Relaxed', 'Safe', 'Thoughtful', 'Centred', 'Rested', 'Patient', 'Accepted'] },
];
